Repository boostcampwm2023/web06-CodeClash, pull requests merged in 2023-12, with the labels that each got.

#181 [FE] 음원변경
  frontend/public/music/RDD.mp3
  frontend/public/music/STH.mp3
  frontend/public/music/SZG.mp3
  frontend/public/music/URMan.mp3
  frontend/src/components/gameplay/gameitem/gameItemHandler.ts
  frontend/src/components/gameplay/problemType.ts
  frontend/src/components/lobby/RoomListBox.tsx
  frontend/src/components/room/UserCard.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/pages/RoomPage.tsx
  frontend/src/store/useLobby.ts
  frontend/src/store/useLogin.ts
  frontend/src/store/useRoom.ts
Labels: Feat, Fe

#185 [BE] Feat: solution 함수 리턴값 ipc 전송 방식으로 변경
  scoring-server/codeRunner.js
Labels: enhancement, Feat

#184 [BE] Fix: 문제의 테스트케이스를 하나만 가져오는 문제
  api-server/src/problems/problems.service.ts
Labels: Fix, Be

#186 [BE] Deploy: 채점 서버 최신으로 배포
  scoring-server/Dockerfile
  scoring-server/codeRunner.js
Labels: Deploy

#195 [BE] Feat: 예외 필터 전역화, 로비 입장 소켓 연결과 분리, 방 입장과 정보 받아오는 로직 분리, 이벤트 응답을 return으로 전달
  api-server/package-lock.json
  api-server/package.json
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Refactor, Be

#194 [BE] Feat: 유저의 성공, 실패 여부를 새로운 컬럼에 저장하는 기능 구현
  api-server/src/scores/scores.service.ts
  api-server/src/users/entities/user.entity.ts
  api-server/src/users/users.service.ts
Labels: Feat

#198 [BE] Refactor: 방의 userList에 소켓이 아닌 커스텀 객체를 담도록 수정
  api-server/src/rooms/dtos/rooms.user.dto.ts
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/entities/rooms.user.entity.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Refactor, Be

#202 fix: 방 아이디가 제대로 전달되지 않는 문제 수정
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#205 [BE] Fix: 로비 정보에 roomList 전송하지 않는 문제 수정
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#207 [BE] Fix: 구조분해할당 오류 수정
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#209 [BE] Feat: 방 입퇴장시 유저카운트 갱신, 기본 방 제목 추가
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#214 [BE] Feature: 아이템 생성, 사용 검증
  api-server/src/rooms/dtos/rooms.user.dto.ts
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#216 [BE] Feat: 아이템 생성 타이머 자동삭제
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#218 [BE} Fix: Get으로는 body를 사용할 수 없기때문에, query parameter로 변경
  api-server/src/submissions/dto/search-submission.dto.ts
  api-server/src/submissions/submissions.controller.ts
  api-server/src/submissions/submissions.module.ts
  api-server/src/submissions/submissions.service.ts
Labels: Feat, Refactor, Be

#217 [BE] Refactor: dm 기능 에러처리 분리
  api-server/src/rooms/entities/rooms.user.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Refactor, Be

#222 [BE] Refactor: 강퇴 게이트웨이
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Refactor, Be

#223 [BE] Refactor: 초대 게이트웨이 예외처리 추가, 리턴값 변경, 방 상태 타입 추가
  api-server/src/rooms/dtos/rooms.invite.dto.ts
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Refactor, Be

#192 [FE] feat: 로비, 방 디버깅 및 표시 내용 수정
  frontend/src/api/user.ts
  frontend/src/components/lobby/MyInfo.tsx
  frontend/src/components/lobby/RoomListBox.tsx
  frontend/src/components/lobby/UserInfoModal.tsx
  frontend/src/components/login/InputBox.tsx
  frontend/src/components/room/ButtonBox.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/pages/RoomPage.tsx
  frontend/src/store/useRoom.ts
  frontend/src/utils/calc.ts
Labels: Feat, Fe

#206 [BE] Deploy: be api server
  api-server/src/auth/auth.controller.ts
  api-server/src/rooms/dtos/rooms.invite.dto.ts
  api-server/src/rooms/dtos/rooms.user.dto.ts
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/entities/rooms.user.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
  api-server/src/submissions/dto/search-submission.dto.ts
  api-server/src/submissions/submissions.controller.spec.ts
  api-server/src/submissions/submissions.controller.ts
  api-server/src/submissions/submissions.module.ts
  api-server/src/submissions/submissions.service.ts
  api-server/src/users/users.controller.ts
Labels: Be, Deploy

#225 [BE] Feature: 밴리스트 추가
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#228 [BE] Fix: 서버가 간헐적으로 종료되는 문제
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#229 [BE] Fix: 아이템 생성 타이머 제거 메서드 수정, 로깅
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#230 [BE] Fix: 소켓 객체를 제대로 불러오지 못하는 문제
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#231 [BE] Fix: 소켓 객체 네임스페이스 문제 수정
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#232 Fix: 네임스페이스 경로 수정
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#233 [BE] Fix: 소켓 매퍼 객체 생성
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#234 [BE] Fix: 아이템 생성 중복 실행
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#235 [BE] Fix: 비동기 처리 수정
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#236 [FE] Deploy: api 변경 반영
  frontend/src/api/user.ts
  frontend/src/components/lobby/MyInfo.tsx
  frontend/src/components/lobby/RoomListBox.tsx
  frontend/src/components/lobby/UserInfoModal.tsx
  frontend/src/components/login/InputBox.tsx
  frontend/src/components/player/MusicPlayer.tsx
  frontend/src/components/protectroute/ProtectRoute.tsx
  frontend/src/components/result/ButtonBox.tsx
  frontend/src/components/result/CodeViewerBox.tsx
  frontend/src/components/result/RankBox.tsx
  frontend/src/components/result/RankItem.tsx
  frontend/src/components/result/SummaryBox.tsx
  frontend/src/components/room/ButtonBox.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/pages/ResultPage.tsx
  frontend/src/pages/RoomPage.tsx
  frontend/src/store/useRoom.ts
  frontend/src/utils/calc.ts
  frontend/tailwind.config.js
Labels: Fe, Deploy

#237 [BE] Fix: 방 객체 가져올 때 예외처리 통합
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#239 [BE] Fix: 방 입장시 예외처리 추가, 테스트용 로그
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#240 [BE] Fix: 에러 처리를 위한 로그 추가
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#243 [BE] Fix: 소켓 재연결 조건 추가
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#246 [BE] Refactor: 사용하지 않는 로그 삭제, 이벤트 타입 반환 추가
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Refactor, Be

#248 [BE] Feat: 게임 시작시에도 아이템 1개 전달
  api-server/src/rooms/rooms.gateway.ts
Labels: Feat, Be

#249 [BE] Fix: 로비, 방 정보 반환 오류 수정
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#250 [Be] Fix: 이벤트 이름 반환 삭제
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#251 [BE] Fix: 아이템 분배 순서 변경
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#253 [BE] Refactor: 아이템 첫 분배 setTimeout으로 변경
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
Labels: Refactor, Be

#252 [BE] Feat: 런타임 동안에, memory track 기능 추가.
  scoring-server/codeRunner.js
  scoring-server/memoryTracker.js
  scoring-server/package-lock.json
  scoring-server/package.json
Labels: Feat, Be

#255 [BE] Feat: 제출 게이트웨이, 유저 순위, 게임 종료 카운트다운
  api-server/src/rooms/dtos/rooms.user.dto.ts
  api-server/src/rooms/entities/rooms.user.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.module.ts
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#258 [BE] Feat: 초대 이벤트 응답에 방 이름, 초대한 유저 이름 추가
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#261 [BE] Fix: submission의 hashcode select에서 삭제
  api-server/src/submissions/submissions.service.ts
Labels: Fix, Be

#263 [BE] Fix: 실행, 제출 구분
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#264 [BE] Fix: 통과시 랭킹 매기는 로직, 로깅
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#227 [FE] fix: 리팩토링
  frontend/src/components/lobby/MyInfo.tsx
  frontend/src/components/lobby/RoomListBox.tsx
  frontend/src/components/lobby/UserInfoModal.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/store/useLobby.ts
Labels: Fix, Fe

#259 [FE] feat: 초대 기능 추가
  frontend/src/components/lobby/Header.tsx
  frontend/src/components/lobby/InviteModal.tsx
  frontend/src/components/lobby/UserListBox.tsx
  frontend/src/components/room/ButtonBox.tsx
  frontend/src/components/room/InviteModal.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/store/useLobby.ts
Labels: Feat, Fe

#271 [BE] Feat: 방 입장 예외처리 추가
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Feat, Be

#273 [BE] Fix: 클라이언트에 에러가 전달되지 않는 문제
  api-server/src/common/exception-filter/http-to-ws.exception.ts
  api-server/src/common/exception-filter/ws.exception.filter.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#274 [BE] Fix: 통과한 유저는 아이템을 받지 않도록 수정
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#275 [BE] Feat: 전체 플레이, 승리 횟수 증가
  api-server/src/rooms/rooms.gateway.ts
Labels: Feat, Be

#226 [BE] Deploy: 백엔드 api server 배포
  api-server/src/common/exception-filter/http-to-ws.exception.ts
  api-server/src/common/exception-filter/ws.exception.filter.ts
  api-server/src/rooms/dtos/rooms.user.dto.ts
  api-server/src/rooms/entities/room.entity.ts
  api-server/src/rooms/entities/rooms.user.entity.ts
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.spec.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.module.ts
  api-server/src/rooms/rooms.service.ts
  api-server/src/scores/scores.module.ts
  api-server/src/scores/scores.service.ts
  api-server/src/submissions/dto/create-submission.dto.ts
  api-server/src/submissions/entities/submission.entity.ts
  api-server/src/submissions/submissions.service.ts
Labels: Be, Deploy

#276 [BE] Fix: 제출하지 않았을 때 기본 랭킹 수정
  api-server/src/rooms/rooms.constants.ts
Labels: Fix, Be

#267 [FE] feat: 강퇴 기능 추가
  frontend/src/components/room/UserCard.tsx
  frontend/src/pages/RoomPage.tsx
Labels: Feat, Fe

#279 [BE] Fix: 소켓 연결 해제시 예외처리 추가, 아이템 배분 비동기로 수정
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#281 [BE] Fix: 유저가 2명 이상부터 게임을 시작할 수 있게 변경
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#282 [BE] Fix: 필요없는 DTO 삭제
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be

#284 [FE] fix: 오류 수정
  frontend/src/components/lobby/CreateRoomModal.tsx
  frontend/src/components/lobby/Header.tsx
  frontend/src/components/lobby/InviteModal.tsx
  frontend/src/components/lobby/MyInfo.tsx
  frontend/src/components/lobby/RoomListBox.tsx
  frontend/src/components/lobby/UserListBox.tsx
Labels: Fix, Fe

#277 [BE] Deploy: Dev be api server
  api-server/src/rooms/rooms.constants.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Be, Deploy

#288 [FE] feat: 게임 시작 후 인터렉션 방지
  frontend/src/components/room/ButtonBox.tsx
  frontend/src/components/room/ChatBox.tsx
  frontend/src/pages/RoomPage.tsx
Labels: Feat, Fe

#290 [FE] Feat: 토스트 추가, 게임 처음 시작시 설명 제공
  frontend/src/App.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/ToastItem.tsx
  frontend/src/components/gameplay/Description.tsx
  frontend/src/components/gameplay/FooterBox.tsx
  frontend/src/components/gameplay/InitialGameExplain.tsx
  frontend/src/components/gameplay/ItemButton.tsx
  frontend/src/components/gameplay/PlayBox.tsx
  frontend/src/components/gameplay/gameitem/GameEventHandler.tsx
  frontend/src/components/gameplay/gameitem/gameItemType.ts
  frontend/src/components/lobby/CreateRoomModal.tsx
  frontend/src/components/lobby/Header.tsx
  frontend/src/components/lobby/InviteModal.tsx
  frontend/src/components/lobby/RoomListBox.tsx
  frontend/src/components/login/InputBox.tsx
  frontend/src/components/player/MusicPlayer.tsx
  frontend/src/pages/GamePlayPage.tsx
  frontend/src/pages/RoomPage.tsx
Labels: Feat, Fe
