Repository boostcampwm2023/web06-CodeClash, pull requests merged in 2023-11, with the labels that each got.

#15 Api server 초기 배포
  .dockerignore
  .eslintrc.js
  .github/workflows/main.yml
  .gitignore
  .prettierrc
  Dockerfile
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  src/scores/scores.controller.spec.ts
  src/scores/scores.controller.ts
  src/scores/scores.module.ts
  src/scores/scores.service.spec.ts
  src/scores/scores.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: Init

#17 scoring server 초기 배포
  .dockerignore
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  codeRunner.js
  package-lock.json
  package.json
Labels: Init

#18 User module을 만들고, user table typeorm 설정 및 class validator 설정, mysql 연동, 환경 변수 파일 dev/prod 분리
  .env.development
  .env.production
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: review, Feat

#20 현재 채점 중인지 아닌지 확인하는 endpoint 추가 및 메모리 사용량에 따른 정답 여부 구현
  codeRunner.js
Labels: Feat

#24 JWT 기반 회원가입, email로 로그인 하는 기능 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/register-user.dto.ts
  src/auth/guard/basic-token.guard.ts
  src/users/decorators/user.decorator.ts
  src/users/dto/create-user.dto.ts
  src/users/mocks/repository.mock.ts
  src/users/users.controller.spec.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: Feat

#25 Token guard 구현 및 필요한 부분에 적용, accessToken 재발급 기능 추가, logger interceptor 구현, hash round 환경변수로 관리
  .env.production
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/decorators/token.decorator.ts
  src/auth/guard/bearer-token.guard.ts
  src/common/common.module.ts
  src/common/interceptors/log.interceptor.ts
  src/common/validation-messages/email.validation-message.ts
  src/common/validation-messages/length.validation-message.ts
  src/common/validation-messages/string.validation-message.ts
  src/main.ts
  src/scores/dto/score-submission.dto.ts
  src/scores/scores.controller.ts
  src/scores/scores.module.ts
  src/scores/scores.service.ts
Labels: Feat, Refactor

#26 채점 서버 최신 버전으로 배포
  codeRunner.js
Labels: Deploy

#33 문제 테이블, 테스트케이스 모듈 생성 및 관련 작업 진행
  src/app.module.ts
  src/auth/guard/admin.guard.ts
  src/common/entities/base-table.entity.ts
  src/problems/dto/create-problem.dto.ts
  src/problems/dto/update-problem.dto.ts
  src/problems/entities/problem.entity.ts
  src/problems/mocks/repository.mock.ts
  src/problems/problems.controller.spec.ts
  src/problems/problems.controller.ts
  src/problems/problems.module.ts
  src/problems/problems.service.spec.ts
  src/problems/problems.service.ts
  src/scores/scores.service.ts
  src/testcases/dto/create-testcase.dto.ts
  src/testcases/dto/update-testcase.dto.ts
  src/testcases/entities/testcase.entity.ts
  src/testcases/mocks/repository.mock.ts
  src/testcases/testcases.controller.spec.ts
  src/testcases/testcases.controller.ts
  src/testcases/testcases.module.ts
  src/testcases/testcases.service.spec.ts
  src/testcases/testcases.service.ts
  src/users/entities/user.entity.ts
Labels: enhancement, Feat

#32 큐 도입으로 요청을 한번에 하나만 처리할 수 있게 만들었습니다.[임시 PR]
  .github/workflows/main.yml
  codeRunner.js
  package-lock.json
  package.json
Labels: Feat

#35 Submission 모듈 생성 및 api 엔드포인트 수정, problem 테이블 수정
  src/app.module.ts
  src/problems/dto/create-problem.dto.ts
  src/problems/entities/problem.entity.ts
  src/problems/mocks/repository.mock.ts
  src/problems/problems.controller.ts
  src/problems/problems.service.ts
  src/scores/dto/score-submission.dto.ts
  src/submissions/dto/create-submission.dto.ts
  src/submissions/dto/update-submission.dto.ts
  src/submissions/entities/submission.entity.ts
  src/submissions/mocks/repository.mock.ts
  src/submissions/submissions.controller.spec.ts
  src/submissions/submissions.controller.ts
  src/submissions/submissions.module.ts
  src/submissions/submissions.service.spec.ts
  src/submissions/submissions.service.ts
  src/testcases/dto/create-testcase.dto.ts
  src/testcases/entities/testcase.entity.ts
  src/testcases/testcases.controller.ts
  src/testcases/testcases.service.ts
  src/users/entities/user.entity.ts
Labels: Feat, Refactor

#76 Be/feature cookie parser
  package-lock.json
  package.json
  src/auth/guard/bearer-token.guard.ts
  src/main.ts
  src/rooms/rooms.gateway.ts
  src/rooms/rooms.service.ts
Labels: Feat, Fix

#81 [BE] fix: 방 입/퇴장시 정보 갱신 문제 수정
  src/rooms/rooms.gateway.ts
  src/rooms/rooms.service.ts
Labels: Fix, Be

#95 프론트엔드 CI/CD 환경 구축
  .github/workflows/front-deploy.yml
Labels: Chore

#97 Update namespace in RoomsGateway
  src/rooms/rooms.gateway.ts
Labels: Fix

#106 [Chore] api server, scoring server 깃 액션 설정
  .github/workflows/api-server-deploy.yml
  .github/workflows/scoring-server-deploy.yml
Labels: Chore

#109 [FE] fix: 여러 브라우저 사이즈에 대응하도록 변경
  frontend/src/App.tsx
  frontend/src/assets/svg/Logo.tsx
  frontend/src/components/login/InputBox.tsx
  frontend/src/components/login/LoginLogo.tsx
  frontend/src/components/player/MusicPlayer.tsx
  frontend/src/components/room/ChatBox.tsx
  frontend/src/components/room/ChatContent.tsx
  frontend/src/components/room/UserCard.tsx
  frontend/src/index.css
  frontend/src/pages/LobbyPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RoomPage.tsx
  frontend/src/store/useSocket.ts
  frontend/tailwind.config.js
Labels: Fix, Fe

#111 [BE] fix: 방을 나가기 전의 userCount를 받아오는 문제
  src/rooms/rooms.gateway.ts
Labels: Fix, Be

#125 [BE] fix: 방이 없어지는 경우 로비에 있는 유저들에게 없어진 방 정보 전송하지 않는 문제
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#130 [BE} Chore: 도커 컨테이너 리소스 제한 및 seccomp 등록
  .github/workflows/scoring-server-deploy.yml
Labels: Chore, Be

#129 [BE] Feat: 예제 케이스에 따라 답 제공
  scoring-server/codeRunner.js
Labels: Refactor

#137 [BE] Chore: api 서버 배포파일 로컬 디렉토리 마운팅
  .github/workflows/api-server-deploy.yml
Labels: Chore, Be

#127 [FE] Feature:채점 api 연동
  frontend/src/api/baseAxios.ts
  frontend/src/api/problem.ts
  frontend/src/api/refresh.ts
  frontend/src/components/gameplay/CodeEditor.tsx
  frontend/src/components/gameplay/Description.tsx
  frontend/src/components/gameplay/FooterBox.tsx
  frontend/src/components/gameplay/PlayBox.tsx
  frontend/src/components/gameplay/gameitem/GameEventHandler.tsx
  frontend/src/components/gameplay/problemType.ts
  frontend/src/pages/GamePlayPage.tsx
  frontend/src/store/useLogin.ts
Labels: Feat, Fe

#140 [BE] Feat: api 서버 로거 객체 구현
  api-server/package-lock.json
  api-server/package.json
  api-server/src/main.ts
  api-server/src/utils/logger/winston.config.ts
Labels: Feat, Be

#139 [BE] Feat: 문제 id 배열로 받는 기능 엔드포인트 추가
  api-server/src/problems/problems.controller.ts
  api-server/src/problems/problems.service.ts
Labels: Feat

#142 [BE] chore: 필요없는 의존성 제거, nestFactory 누락 추가
  api-server/src/main.ts
  api-server/src/utils/logger/winston.config.ts
Labels: Chore, Be

#143 [BE] Fix: socket.data가 undefined 경우 예외처리
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
Labels: Fix, Be

#146 [BE] Chore: moment-timezone 의존성 누락 추가
  api-server/package-lock.json
  api-server/package.json
Labels: Chore, Be

#147 [BE] Feat: 유저 로그인, 회원가입 시 이름, 이메일 전달.
  api-server/src/auth/auth.controller.ts
  api-server/src/auth/auth.service.ts
Labels: Feat

#145 [BE] Deploy: dev 브랜치 배포
  api-server/package-lock.json
  api-server/package.json
  api-server/src/auth/auth.controller.ts
  api-server/src/auth/auth.service.ts
  api-server/src/main.ts
  api-server/src/problems/problems.controller.ts
  api-server/src/problems/problems.service.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.service.ts
  api-server/src/utils/logger/winston.config.ts
Labels: Be, Deploy

#152 [BE] Fix: 로거 설정 오타 수정
  api-server/src/utils/logger/winston.config.ts
Labels: Fix, Be

#144 [FE] Feature: 로그아웃 기능 추가
  frontend/src/components/lobby/Header.tsx
  frontend/src/components/lobby/InviteModal.tsx
  frontend/src/components/lobby/MyInfo.tsx
  frontend/src/components/login/InputBox.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/store/useLogin.ts
  frontend/src/store/useSocket.ts
Labels: Feat, Fe

#151 [FE] Feature: 페이지 슬라이드 모션 추가
  frontend/src/api/problem.ts
  frontend/src/components/common/SlidePage.tsx
  frontend/src/components/room/ReadyMark.tsx
  frontend/src/components/room/UserCard.tsx
  frontend/src/pages/GamePlayPage.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RoomPage.tsx
Labels: Feat, Fe

#154 [BE] Feature: 게이트웨이 유저 아이템 사용 처리 구현
  api-server/src/rooms/rooms.gateway.ts
Labels: Feat, Be

#156 [BE] Feature: 게임 시작시 로비에 게임 시작한 방 전송
  api-server/src/rooms/rooms.gateway.ts
Labels: Feat, Be

#150 [BE] Deploy: 로거 수정본 배포
  api-server/src/main.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/utils/logger/winston.config.ts
Labels: Be, Deploy

#159 [BE] Feature: 게임 시작시 클라이언트에게 문제 전달
  api-server/src/problems/problems.service.ts
  api-server/src/rooms/rooms.gateway.ts
  api-server/src/rooms/rooms.module.ts
Labels: Feat, Be

#162 [FE] feat: 방 입장 퇴장 메시지 출력 및 버그 수정
  frontend/src/components/room/ChatBox.tsx
  frontend/src/components/room/ChatContent.tsx
  frontend/src/pages/RoomPage.tsx
  frontend/src/store/useRoom.ts
Labels: Feat, Fix, Fe

#163 [BE] Feat: SubmissionStatus 구현
  api-server/src/scores/scores.service.ts
  api-server/src/submissions/entities/submission.entity.ts
Labels: Feat

#164 [BE] Refactor: 문제와 테스트케이스를 join해서 가져오는 로직 수정
  api-server/src/problems/problems.service.ts
Labels: Refactor, Be

#166 [BE] Refactor: 랜덤으로 문제 가져오는 로직 수정
  api-server/src/problems/problems.service.ts
  api-server/src/rooms/rooms.gateway.ts
Labels: Refactor, Be

#165 [FE] Feat: 게임 아이템 소켓으로 통신되도록 연결
  frontend/src/assets/avatar/0.webp
  frontend/src/assets/avatar/1.webp
  frontend/src/assets/avatar/10.webp
  frontend/src/assets/avatar/11.webp
  frontend/src/assets/avatar/12.webp
  frontend/src/assets/avatar/13.webp
  frontend/src/assets/avatar/14.webp
  frontend/src/assets/avatar/15.webp
  frontend/src/assets/avatar/16.webp
  frontend/src/assets/avatar/17.webp
  frontend/src/assets/avatar/18.webp
  frontend/src/assets/avatar/19.webp
  frontend/src/assets/avatar/2.webp
  frontend/src/assets/avatar/20.webp
  frontend/src/assets/avatar/3.webp
  frontend/src/assets/avatar/4.webp
  frontend/src/assets/avatar/5.webp
  frontend/src/assets/avatar/6.webp
  frontend/src/assets/avatar/7.webp
  frontend/src/assets/avatar/8.webp
  frontend/src/assets/avatar/9.webp
  frontend/src/components/gameplay/gameitem/GameEventHandler.tsx
  frontend/src/pages/GamePlayPage.tsx
  frontend/src/utils/avatar.ts
Labels: Feat, Fe

#168 [FE] Feat: svg props 이름 변경, 아바타 기능 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/svg/DelaySvg.tsx
  frontend/src/assets/svg/ShuffleSvg.tsx
  frontend/src/assets/svg/SmallWordSvg.tsx
  frontend/src/assets/svg/StoleEyeSvg.tsx
  frontend/src/assets/svg/SwapSvg.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/lobby/MyInfo.tsx
  frontend/src/components/room/UserCard.tsx
  frontend/src/pages/LobbyPage.tsx
  frontend/src/pages/RoomPage.tsx
Labels: Feat, Fe

#169 [BE] Feat: user 회원가입 validation, 유저 제출 코드 가져올 때 문제 정보 추가, 제출 코드 검증 기능
  api-server/src/common/validation-messages/email.validation-message.ts
  api-server/src/common/validation-messages/length.validation-message.ts
  api-server/src/common/validation-messages/string.validation-message.ts
  api-server/src/main.ts
  api-server/src/scores/scores.service.ts
  api-server/src/submissions/entities/submission.entity.ts
  api-server/src/submissions/submissions.service.ts
  api-server/src/users/entities/user.entity.ts
  api-server/src/users/users.service.ts
Labels: Feat

#176 fix: 랜덤 문제 전달되지 않는 문제 수정
  api-server/src/rooms/rooms.gateway.ts
Labels: Fix, Be
